### ISSUE TITLE
Form Wizards

### ISSUE THREAD

**Issue by Talha5** [mwlang/gentelella-rails#11]
We dont have Form wizards in these sample rails app, however its present in the original one. Will it be added or i should proceed on my own? Thanks!

**Comment by mwlang** [comment]
@Talha5 I answered on https://github.com/mwlang/gentelella-rails-demo/issues/1 since this isn't part of the gem itself, so will close this issue here.

This is a hobby project for me.  If you port the pages on the demo as described, I'll accept the pull request.
