### ISSUE TITLE
couldn't find file 'chart' with type 'application/javascript'

### ISSUE THREAD

**Issue by usabi** [mwlang/gentelella-rails#6]
Hello, first of all thanks for the gem :)

After installed the gem, when load the application I have the next error:
ActionView::Template::Error (couldn't find file 'chart' with type 'application/javascript'
Checked in these paths:
  /Users/usabi/Desarrollo/nani/app/assets/config
  /Users/usabi/Desarrollo/nani/app/assets/images
  /Users/usabi/Desarrollo/nani/app/assets/javascripts
  /Users/usabi/Desarrollo/nani/app/assets/stylesheets
  /Users/usabi/.rvm/gems/ruby-2.3.1/gems/parsley-rails-2.7.0.0/vendor/assets/javascripts
....

If I comment out the line which includes the chart library in gentelella.coffee, the problem seems solved.
I don't find the charts.js on your assets files, although I see chart-js-rails in your Gemspec file.
Thanks in advance :)

**Comment by wilsontov** [comment]
I have the same problem

**Comment by mwlang** [comment]
What's the URL (i.e. controller/action) that leads to this error?

**Comment by oivoodoo** [comment]
@mwlang I've just created the pull request: https://github.com/mwlang/gentelella-rails/pull/7

**Comment by mwlang** [comment]
merged!  @usabi and @wilsontov Can you confirm this works for you?

**Comment by Miccighel** [comment]
I installed Gelentella with gem today and i also have this issue
![cattura](https://user-images.githubusercontent.com/6783459/26975230-28be3afc-4d1f-11e7-94b2-81288b17893e.PNG)

**Comment by mwlang** [comment]
I have just now released v0.1.5 that fixes the chart.js issue.  @Miccighel can you confirm this fixes your issue?

**Comment by Miccighel** [comment]
Now it works for me. Thanks!

**Comment by sadmad** [comment]
how you solve this I have this problem on admin lte

**Comment by oivoodoo** [comment]
Hi @sadmad . Please check the pull request https://github.com/mwlang/gentelella-rails/pull/7 

it was the issue with require of js file.

**Comment by gsum** [comment]
-For me I got the same error because webpacker was not running
-so started the server with webpacker and  evrything works

**Comment by asad-shakil** [comment]
> -For me I got the same error because webpacker was not running
> -so started the server with webpacker and evrything works

This has solved my problem.
