### ISSUE TITLE
Problem with the fullcalendar.js asset

### ISSUE THREAD

**Issue by Miccighel** [mwlang/gentelella-rails#8]
When i use your instructions to load all the assets of Gentelella, those .js asset gives an Uncaugt TypeError e stops the rendering of the page. May you give a look to that problem?

In a local installation i replaced fullcalendar.js with a blank file and this problem got solved. Obviously, it's not a proper thing to do. 

![cattura](https://user-images.githubusercontent.com/6783459/28227406-0b462044-68da-11e7-865d-daea393818c1.PNG)
![cattura2](https://user-images.githubusercontent.com/6783459/28227407-0b4f268a-68da-11e7-8bb5-ee6c2a08e321.PNG)

**Comment by Miccighel** [comment]
![cattura](https://user-images.githubusercontent.com/6783459/28227608-021923ee-68db-11e7-9ce2-ad1ae3941b70.PNG)

**Comment by xingyuli** [comment]
Integrate with my demo app, and came across the same problem. It breaks the click event of navigation bar.

![image](https://user-images.githubusercontent.com/3337431/28256809-405576a2-6af8-11e7-9371-92e1f1688755.png)

**Comment by mwlang** [comment]
It looks like I may have made a mistake with including fullcalendar.js in the gem's core require file.  When I tested this out on the gentelella-rails demo app, I discovered, fullcalendar.js is in the app/assets/javascripts folder, but not in the gem's asset pipeline. 

I am out of time for now, but will review this some more later.  At least for now, we know where and why!

**Comment by Miccighel** [comment]
That was precisely the problem. Thank you for having found it!

**Comment by mwlang** [comment]
Coming back to this first thing in the morning with a fresh mind, I see that the fullcalendar.js script and stylesheets are all in the right place in the gem.  I was misreading the code last night.

I need to figure out how to replicate your results above in order to solve at this point.  Can you make a small rails project which reproduces your error above?

**Comment by mwlang** [comment]
This was related to #9 and resolved at same time #9 was resolved.
